---
- name: JBoss EAP migration
  hosts: all
  become: true
  gather_facts: false
  strategy: free
  vars:
    current_eap_home: "/opt/wildfly-14.0.1.Final/"
    new_eap_home: "/opt/wildfly-17.0.1.Final"

  tasks:
    - name: Copy and extract jboss eap compress file to remote machine
      unarchive:
        src: "{{ pkg_location | default('files') }}/wildfly-17.0.1.Final.zip"
        dest: /opt/
        owner: wildfly
        group: wildfly

    - name: Copy and extract jboss eap compress file to remote machine
      unarchive:
        src: "{{ pkg_location | default('files') }}/wildfly-server-migration.tar"
        dest: /opt/
        owner: wildfly
        group: wildfly

    - name: copy the server migration script
      copy:
        src: "{{ pkg_location | default('files') }}/jboss-server-migration.sh"
        dest: "{{ new_eap_home }}/bin"
        mode: '0755'

    - name: Migrate configuration
      command: ./jboss-server-migration.sh -s "{{ current_eap_home }}" -t "{{ new_eap_home }}" -i false
      args:
        chdir: "/opt/wildfly-server-migration/dist/standalone/target/jboss-server-migration"
      register: resultado

    - name: Migration Results
      debug: 
        msg: "{{resultado.stdout}}"
